name: Build OpenWrt luci-app-mihomo-status (x86_64 only)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib gettext git libncurses-dev libssl-dev python3 \
            python3-pip rsync unzip zlib1g-dev file wget libelf-dev ccache

      - name: Download OpenWrt SDK (x86_64)
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/x86/64/openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          mv openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64 openwrt-sdk

      - name: Move package into SDK
        run: |
          mkdir -p openwrt-sdk/package/luci-app-mihomo-status
          cp -r luci-app-mihomo-status/* openwrt-sdk/package/luci-app-mihomo-status/

      - name: Prepare SDK config
        working-directory: ./openwrt-sdk
        run: |
          echo 'CONFIG_PACKAGE_luci-app-mihomo-status=m' >> .config
          make defconfig

      - name: Build package
        working-directory: ./openwrt-sdk
        run: |
          make package/luci-app-mihomo-status/compile V=s -j$(nproc)

      - name: Upload built IPK
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-mihomo-status-ipk
          path: openwrt-sdk/bin/packages/*/*/luci-app-mihomo-status_*.ipk
