name: Build luci-app-mihomo-status

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3 python3-pip python3-venv unzip zlib1g-dev file wget

    - name: Download OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/releases/23.05.3/targets/x86/64/openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar -xf openwrt-sdk-*.tar.xz
        mv openwrt-sdk-* openwrt-sdk

    - name: Prepare build environment
      run: |
        cd openwrt-sdk
        ./scripts/feeds update -a || true
        ./scripts/feeds install -a || true
        mkdir -p package/luci-app-mihomo-status
        cp -r ../luci-app-mihomo-status/* package/luci-app-mihomo-status/

    - name: Build luci-app-mihomo-status
      run: |
        cd openwrt-sdk
        make defconfig
        make package/luci-app-mihomo-status/compile V=s

    - name: Upload compiled IPK
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-mihomo-status-ipk
        path: |
          openwrt-sdk/bin/packages/*/*/luci-app-mihomo-status*.ipk
