name: Build luci-app-mihomo-status

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget python3

    - name: Download OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar -Jxf openwrt-sdk-*.tar.xz
        mv openwrt-sdk-* sdk

    - name: Move plugin into SDK package directory
      run: |
        mkdir -p sdk/package/luci-app-mihomo-status
        cp -r ./luci-app-mihomo-status/* sdk/package/luci-app-mihomo-status/

    - name: Update feeds & prepare
      run: |
        cd sdk
        ./scripts/feeds update -a || true
        ./scripts/feeds install -a || true
        make defconfig

    - name: Build luci-app-mihomo-status
      run: |
        cd sdk
        make package/luci-app-mihomo-status/compile V=s

    - name: Upload compiled IPK
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-mihomo-status-ipk
        path: |
          sdk/bin/packages/*/*/luci-app-mihomo-status_*.ipk
