name: Build luci-app-mihomo-status

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            rsync unzip zlib1g-dev file wget python3 python3-pip

      - name: Download and extract OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-22.03.5-x86-64_*.tar.xz
          SDK_DIR=$(tar -tf openwrt-sdk-22.03.5-x86-64_*.tar.xz | head -1 | cut -f1 -d"/")
          mv "$SDK_DIR" sdk

      - name: Copy plugin into SDK
        run: |
          mkdir -p sdk/package/luci-app-mihomo-status
          cp -r luci-app-mihomo-status/* sdk/package/luci-app-mihomo-status/

      - name: Build package
        run: |
          cd sdk
          make defconfig
          make package/luci-app-mihomo-status/compile -j$(nproc) V=s

      - name: Upload .ipk
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-mihomo-status
          path: sdk/bin/packages/x86_64/base/luci-app-mihomo-status_*.ipk
